version: '3.8'

services:
  card_checker:
    container_name: card_backend
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    ports:
      - '${HOST_PORT}:8080'
    env_file:
    - .env
    deploy:
      mode: replicated
      replicas: 1
